dataset_path: data/COVID19
resample_num: 21

# 每次训练几个病人
#batch_size: 256  #X
#batch_size: 32  #Y
batch_size: 6 #Z

# initial learning rate
learning_rate: 0.0001
# weight decay
weight_decay: 0

# 默认保存的模型，如果提供，下次将保存的模型开始训练。
resume: false
# 预训练模型，如果提供，将从预训练模型载入进行训练。
pertrain_path: null
# 模型保存路径
checkpoint_dir: ./checkpoint/

# A manual rescaling weight given to each class.
loss_weight: null
#loss_weight: 0.1:1.
# max number of epochs
epochs: 4000
# max number of iterations
iters: 100000000
# number of epochs with no loss improvement after which the training will be stopped
patience: 25
# ##################################
# 网络参数
#model
model: UResNet
# 初始的特征图数量
init_channel_number: 16
# loss function to be used during training (ce - CrossEntropy)
loss: dice
#loss: focal
# 多分类使用softmax，单分类使用sigmoid
final_sigmoid: True
# number of input channels to the model，灰度数据使用单通道
in_channels: 1
# number of output channels
out_channels: 1
# a target value that is ignored and does not contribute to the input gradient，用不到
ignore_index: Null
# use simple Curriculum Learning scheme if ignore_index is present，用不到
curriculum: False
# use nn.Upsample for upsampling in the decoder path instead of ConvTranspose3d，上采样是否使用插值法
interpolate: False
# determines the order of operators in a single layer (crg - Conv3d+ReLU+GroupNorm)，默认
#layer_order: cgr
